// frontend/vue/src/views/admin/AdminDashboard.vue
<template>
  <div class="admin-dashboard">
    <div class="dashboard-header">
      <h1>Admin Dashboard</h1>
      <div class="user-info">
        <span>{{ currentUser?.name }}</span>
        <button @click="signOut" class="btn-secondary">Sign Out</button>
      </div>
    </div>

    <div class="dashboard-tabs">
      <button 
        v-for="tab in tabs" 
        :key="tab.id"
        @click="activeTab = tab.id"
        :class="['tab-button', { active: activeTab === tab.id }]"
      >
        {{ tab.label }}
      </button>
    </div>

    <div class="dashboard-content">
      <AnalyticsDashboard v-if="activeTab === 'analytics'" />
      <DataManagement v-if="activeTab === 'data'" />
      <AppConfiguration v-if="activeTab === 'config'" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { useAnalytics } from '../../services/analytics';
import { getCurrentUser, signOut as authSignOut } from '../../graphql/client';
import AnalyticsDashboard from './AnalyticsDashboard.vue';
import DataManagement from './DataManagement.vue';
import AppConfiguration from './AppConfiguration.vue';

const { trackAction, trackError } = useAnalytics('admin-dashboard');

const activeTab = ref('analytics');
const currentUser = ref<any>(null);

const tabs = [
  { id: 'analytics', label: '📊 Analytics' },
  { id: 'data', label: '🗃️ Data Management' },
  { id: 'config', label: '⚙️ Configuration' }
];

onMounted(async () => {
  try {
    currentUser.value = await getCurrentUser();
    trackAction('dashboard-loaded');
  } catch (error) {
    trackError('failed-to-load-user', { error: error.message });
  }
});

const signOut = async () => {
  try {
    trackAction('admin-signout');
    await authSignOut();
  } catch (error) {
    trackError('signout-failed', { error: error.message });
  }
};
</script>

<style scoped>
.admin-dashboard {
  min-height: 100vh;
  background: #f5f5f5;
}

.dashboard-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 1rem 2rem;
  background: white;
  border-bottom: 1px solid #e0e0e0;
}

.dashboard-header h1 {
  margin: 0;
  color: #333;
}

.user-info {
  display: flex;
  align-items: center;
  gap: 1rem;
}

.dashboard-tabs {
  display: flex;
  background: white;
  border-bottom: 1px solid #e0e0e0;
}

.tab-button {
  padding: 1rem 2rem;
  border: none;
  background: none;
  cursor: pointer;
  border-bottom: 3px solid transparent;
  transition: all 0.2s;
}

.tab-button:hover {
  background: #f0f0f0;
}

.tab-button.active {
  border-bottom-color: #007bff;
  color: #007bff;
}

.dashboard-content {
  padding: 2rem;
}

.btn-secondary {
  padding: 0.5rem 1rem;
  border: 1px solid #ccc;
  background: white;
  border-radius: 4px;
  cursor: pointer;
}

.btn-secondary:hover {
  background: #f0f0f0;
}
</style>

// frontend/react/src/views/admin/AdminDashboard.tsx
import React, { useState, useEffect } from 'react';
import { useAnalytics } from '../../services/analytics';
import AnalyticsDashboard from './AnalyticsDashboard';
import DataManagement from './DataManagement';
import AppConfiguration from './AppConfiguration';
import './AdminDashboard.css';

interface Tab {
  id: string;
  label: string;
}

const AdminDashboard: React.FC = () => {
  const { trackAction, trackError } = useAnalytics('admin-dashboard');
  const [activeTab, setActiveTab] = useState('analytics');
  const [currentUser, setCurrentUser] = useState<any>(null);

  const tabs: Tab[] = [
    { id: 'analytics', label: '📊 Analytics' },
    { id: 'data', label: '🗃️ Data Management' },
    { id: 'config', label: '⚙️ Configuration' }
  ];

  useEffect(() => {
    loadCurrentUser();
  }, []);

  const loadCurrentUser = async () => {
    try {
      // This would get current user from auth service
      setCurrentUser({ name: 'Admin User' });
      trackAction('dashboard-loaded');
    } catch (error) {
      trackError('failed-to-load-user', { error: error.message });
    }
  };

  const handleSignOut = async () => {
    try {
      trackAction('admin-signout');
      // Implement sign out logic
      window.location.href = '/login';
    } catch (error) {
      trackError('signout-failed', { error: error.message });
    }
  };

  const renderTabContent = () => {
    switch (activeTab) {
      case 'analytics':
        return <AnalyticsDashboard />;
      case 'data':
        return <DataManagement />;
      case 'config':
        return <AppConfiguration />;
      default:
        return <AnalyticsDashboard />;
    }
  };

  return (
    <div className="admin-dashboard">
      <div className="dashboard-header">
        <h1>Admin Dashboard</h1>
        <div className="user-info">
          <span>{currentUser?.name}</span>
          <button onClick={handleSignOut} className="btn-secondary">
            Sign Out
          </button>
        </div>
      </div>

      <div className="dashboard-tabs">
        {tabs.map(tab => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={`tab-button ${activeTab === tab.id ? 'active' : ''}`}
          >
            {tab.label}
          </button>
        ))}
      </div>

      <div className="dashboard-content">
        {renderTabContent()}
      </div>
    </div>
  );
};

export default AdminDashboard;
