// frontend/angular/src/app/views/admin/admin-dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { AnalyticsService } from '../../services/analytics.service';

interface Tab {
  id: string;
  label: string;
}

@Component({
  selector: 'app-admin-dashboard',
  templateUrl: './admin-dashboard.component.html',
  styleUrls: ['./admin-dashboard.component.css']
})
export class AdminDashboardComponent implements OnInit {
  activeTab = 'analytics';
  currentUser: any = null;

  tabs: Tab[] = [
    { id: 'analytics', label: '📊 Analytics' },
    { id: 'data', label: '🗃️ Data Management' },
    { id: 'config', label: '⚙️ Configuration' }
  ];

  constructor(private analyticsService: AnalyticsService) {}

  ngOnInit(): void {
    this.loadCurrentUser();
    this.analyticsService.trackView('admin-dashboard');
  }

  private async loadCurrentUser(): Promise<void> {
    try {
      // This would get current user from auth service
      this.currentUser = { name: 'Admin User' };
      this.analyticsService.trackAction('dashboard-loaded', 'admin-dashboard');
    } catch (error) {
      this.analyticsService.trackError('failed-to-load-user', 'admin-dashboard', { error: error.message });
    }
  }

  setActiveTab(tabId: string): void {
    this.activeTab = tabId;
    this.analyticsService.trackAction('tab-changed', 'admin-dashboard', { tab: tabId });
  }

  async signOut(): Promise<void> {
    try {
      this.analyticsService.trackAction('admin-signout', 'admin-dashboard');
      // Implement sign out logic
      window.location.href = '/login';
    } catch (error) {
      this.analyticsService.trackError('signout-failed', 'admin-dashboard', { error: error.message });
    }
  }
}
<div class="admin-dashboard">
  <div class="dashboard-header">
    <h1>Admin Dashboard</h1>
    <div class="user-info">
      <span>{{ currentUser?.name }}</span>
      <button (click)="signOut()" class="btn-secondary">Sign Out</button>
    </div>
  </div>

  <div class="dashboard-tabs">
    <button 
      *ngFor="let tab of tabs" 
      (click)="setActiveTab(tab.id)"
      [class]="'tab-button ' + (activeTab === tab.id ? 'active' : '')"
    >
      {{ tab.label }}
    </button>
  </div>

  <div class="dashboard-content">
    <app-analytics-dashboard *ngIf="activeTab === 'analytics'"></app-analytics-dashboard>
    <app-data-management *ngIf="activeTab === 'data'"></app-data-management>
    <app-app-configuration *ngIf="activeTab === 'config'"></app-app-configuration>
  </div>
</div>

// frontend/react/src/views/admin/AdminDashboard.tsx
import React, { useState, useEffect } from 'react';
import { useAnalytics } from '../../services/analytics';
import AnalyticsDashboard from './AnalyticsDashboard';
import DataManagement from './DataManagement';
import AppConfiguration from './AppConfiguration';
import './AdminDashboard.css';

interface Tab {
  id: string;
  label: string;
}

const AdminDashboard: React.FC = () => {
  const { trackAction, trackError } = useAnalytics('admin-dashboard');
  const [activeTab, setActiveTab] = useState('analytics');
  const [currentUser, setCurrentUser] = useState<any>(null);

  const tabs: Tab[] = [
    { id: 'analytics', label: '📊 Analytics' },
    { id: 'data', label: '🗃️ Data Management' },
    { id: 'config', label: '⚙️ Configuration' }
  ];

  useEffect(() => {
    loadCurrentUser();
  }, []);

  const loadCurrentUser = async () => {
    try {
      // This would get current user from auth service
      setCurrentUser({ name: 'Admin User' });
      trackAction('dashboard-loaded');
    } catch (error) {
      trackError('failed-to-load-user', { error: error.message });
    }
  };

  const handleSignOut = async () => {
    try {
      trackAction('admin-signout');
      // Implement sign out logic
      window.location.href = '/login';
    } catch (error) {
      trackError('signout-failed', { error: error.message });
    }
  };

  const renderTabContent = () => {
    switch (activeTab) {
      case 'analytics':
        return <AnalyticsDashboard />;
      case 'data':
        return <DataManagement />;
      case 'config':
        return <AppConfiguration />;
      default:
        return <AnalyticsDashboard />;
    }
  };

  return (
    <div className="admin-dashboard">
      <div className="dashboard-header">
        <h1>Admin Dashboard</h1>
        <div className="user-info">
          <span>{currentUser?.name}</span>
          <button onClick={handleSignOut} className="btn-secondary">
            Sign Out
          </button>
        </div>
      </div>

      <div className="dashboard-tabs">
        {tabs.map(tab => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={`tab-button ${activeTab === tab.id ? 'active' : ''}`}
          >
            {tab.label}
          </button>
        ))}
      </div>

      <div className="dashboard-content">
        {renderTabContent()}
      </div>
    </div>
  );
};

export default AdminDashboard;
