// frontend/react/src/components/Posts.tsx
import React, { useState } from 'react';
import { useQuery, useMutation } from '@apollo/client';
import { LIST_POSTS, CREATE_POST, UPDATE_POST, DELETE_POST } from '../graphql/queries';

interface Post {
  id: string;
  title: string;
  content: string;
  userId: string;
  published: boolean;
  createdAt: string;
  updatedAt: string;
  user: {
    id: string;
    name: string;
    email: string;
  };
}

interface PostForm {
  title: string;
  content: string;
  published: boolean;
}

const Posts: React.FC = () => {
  const [showDialog, setShowDialog] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [editingPost, setEditingPost] = useState<Post | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const [postForm, setPostForm] = useState<PostForm>({
    title: '',
    content: '',
    published: false
  });

  const { data, loading, error, refetch } = useQuery(LIST_POSTS);
  const [createPost] = useMutation(CREATE_POST);
  const [updatePost] = useMutation(UPDATE_POST);
  const [deletePost] = useMutation(DELETE_POST);

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString();
  };

  const openCreateDialog = () => {
    setIsEditing(false);
    setEditingPost(null);
    setPostForm({
      title: '',
      content: '',
      published: false
    });
    setShowDialog(true);
  };

  const openEditDialog = (post: Post) => {
    setIsEditing(true);
    setEditingPost(post);
    setPostForm({
      title: post.title,
      content: post.content,
      published: post.published
    });
    setShowDialog(true);
  };

  const closeDialog = () => {
    setShowDialog(false);
    setIsEditing(false);
    setEditingPost(null);
    setPostForm({
      title: '',
      content: '',
      published: false
    });
  };

  const submitPostForm = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitting(true);

    try {
      if (isEditing && editingPost) {
        await updatePost({
          variables: {
            input: {
              id: editingPost.id,
              title: postForm.title,
              content: postForm.content,
              published: postForm.published
            }
          }
        });
      } else {
        await createPost({
          variables: {
            input: {
              title: postForm.title,
              content: postForm.content,
              published: postForm.published
            }
          }
        });
      }

      await refetch();
      closeDialog();
    } catch (err) {
      console.error('Error saving post:', err);
      alert('Failed to save post. Please try again.');
    } finally {
      setSubmitting(false);
    }
  };

  const handleDeletePost = async (post: Post) => {
    if (!confirm(`Are you sure you want to delete "${post.title}"?`)) {
      return;
    }

    try {
      await deletePost({
        variables: {
          input: {
            id: post.id
          }
        }
      });
      await refetch();
    } catch (err) {
      console.error('Error deleting post:', err);
      alert('Failed to delete post. Please try again.');
    }
  };

  if (loading) {
    return (
      <div className="flex justify-center items-center h-64">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500"></div>
        <p className="ml-4 text-gray-600">Loading posts...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="bg-red-50 border border-red-200 rounded-md p-4">
        <p className="text-red-800">Error loading posts: {error.message}</p>
      </div>
    );
  }

  const posts: Post[] = data?.listPosts || [];

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold text-gray-900">Posts</h1>
          <p className="mt-2 text-gray-600">Manage your blog posts</p>
        </div>
        <button
          onClick={openCreateDialog}
          className="bg-blue-600 hover:bg-blue-700 text-white font-medium py-2 px-4 rounded-lg transition-colors duration-200"
        >
          Create Post
        </button>
      </div>

      {/* Posts List */}
      <div className="space-y-6">
        {posts.map((post) => (
          <div key={post.id} className="bg-white rounded-lg shadow p-6">
            <div className="flex items-start justify-between">
              <div className="flex-1">
                <div className="flex items-center mb-2">
                  <span
                    className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                      post.published
                        ? 'bg-green-100 text-green-800'
                        : 'bg-yellow-100 text-yellow-800'
                    }`}
                  >
                    {post.published ? 'Published' : 'Draft'}
                  </span>
                </div>

                <h3 className="text-lg font-semibold text-gray-900 mb-2">
                  {post.title}
                </h3>

                <p className="text-gray-600 mb-4 line-clamp-3">
                  {post.content}
                </p>

                <div className="flex items-center text-sm text-gray-500">
                  <span>By {post.user?.name || 'Unknown User'}</span>
                  <span className="mx-2">•</span>
                  <span>{formatDate(post.createdAt)}</span>
                  {post.updatedAt !== post.createdAt && (
                    <>
                      <span className="mx-2">•</span>
                      <span>Updated {formatDate(post.updatedAt)}</span>
                    </>
                  )}
                </div>
              </div>

              <div className="ml-4 flex-shrink-0 space-x-2">
                <a
                  href={`/posts/${post.id}`}
                  className="inline-flex items-center px-3 py-1 border border-transparent text-sm font-medium rounded-md text-primary-600 bg-primary-50 hover:bg-primary-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500"
                >
                  <svg className="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"></path>
                  </svg>
                  View Post
                </a>
                <button 
                  onClick={() => openEditDialog(post)}
                  className="text-blue-600 hover:text-blue-900 text-sm font-medium"
                >
                  Edit
                </button>
                <button 
                  onClick={() => handleDeletePost(post)}
                  className="text-red-600 hover:text-red-900 text-sm font-medium"
                >
                  Delete
                </button>
              </div>
            </div>
          </div>
        ))}

        {/* Empty State */}
        {posts.length === 0 && (
          <div className="text-center py-12">
            <svg
              className="mx-auto h-12 w-12 text-gray-400"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
              />
            </svg>
            <h3 className="mt-2 text-sm font-medium text-gray-900">No posts</h3>
            <p className="mt-1 text-sm text-gray-500">Get started by creating a new post.</p>
            <button
              onClick={openCreateDialog}
              className="mt-4 bg-blue-600 hover:bg-blue-700 text-white font-medium py-2 px-4 rounded-lg transition-colors duration-200"
            >
              Create Your First Post
            </button>
          </div>
        )}
      </div>

      {/* Create/Edit Dialog */}
      {showDialog && (
        <div className="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full z-50">
          <div className="relative top-20 mx-auto p-5 border w-full max-w-2xl shadow-lg rounded-md bg-white">
            <div className="mt-3">
              <h3 className="text-lg font-medium text-gray-900 mb-4">
                {isEditing ? 'Edit Post' : 'Create New Post'}
              </h3>
              
              <form onSubmit={submitPostForm}>
                <div className="mb-4">
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Title *
                  </label>
                  <input
                    type="text"
                    required
                    value={postForm.title}
                    onChange={(e) => setPostForm(prev => ({ ...prev, title: e.target.value }))}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                    placeholder="Enter post title"
                  />
                </div>

                <div className="mb-4">
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Content *
                  </label>
                  <textarea
                    rows={8}
                    required
                    value={postForm.content}
                    onChange={(e) => setPostForm(prev => ({ ...prev, content: e.target.value }))}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                    placeholder="Write your post content here..."
                  />
                </div>

                <div className="mb-6">
                  <label className="flex items-center">
                    <input
                      type="checkbox"
                      checked={postForm.published}
                      onChange={(e) => setPostForm(prev => ({ ...prev, published: e.target.checked }))}
                      className="rounded border-gray-300 text-blue-600 shadow-sm focus:border-blue-300 focus:ring focus:ring-blue-200 focus:ring-opacity-50"
                    />
                    <span className="ml-2 text-sm text-gray-700">Publish immediately</span>
                  </label>
                </div>

                <div className="flex justify-end space-x-3">
                  <button
                    type="button"
                    onClick={closeDialog}
                    className="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-200 rounded-md hover:bg-gray-300 transition-colors"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    disabled={submitting}
                    className="px-4 py-2 text-sm font-medium text-white bg-blue-600 rounded-md hover:bg-blue-700 transition-colors disabled:opacity-50"
                  >
                    {submitting ? 'Saving...' : (isEditing ? 'Update Post' : 'Create Post')}
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Posts;

// frontend/angular/src/app/views/posts/posts.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { GraphQLClientService } from '../../graphql/client';
import { listPosts, createPost, updatePost, deletePost } from '../../graphql/queries';

interface Post {
  id: string;
  title: string;
  content: string;
  userId: string;
  published: boolean;
  createdAt: string;
  updatedAt: string;
  user: {
    id: string;
    name: string;
    email: string;
  };
}

interface PostForm {
  title: string;
  content: string;
  published: boolean;
}

@Component({
  selector: 'app-posts',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  template: `
    <div class="min-h-screen bg-gray-50 py-8">
      <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <!-- Header -->
        <div class="mb-8">
          <div class="flex justify-between items-center">
            <div>
              <h1 class="text-3xl font-bold text-gray-900">Posts</h1>
              <p class="mt-2 text-gray-600">Manage your blog posts</p>
            </div>
            <button 
              (click)="openCreateDialog()"
              class="btn-primary"
            >
              <svg class="-ml-1 mr-2 h-5 w-5" fill="currentColor" viewBox="0 0 20 20">
                <path fill-rule="evenodd" d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" clip-rule="evenodd"></path>
              </svg>
              New Post
            </button>
          </div>
        </div>

        <!-- Error State -->
        <div *ngIf="error" class="bg-red-50 border border-red-200 rounded-md p-4 mb-6">
          <div class="flex">
            <div class="ml-3">
              <h3 class="text-sm font-medium text-red-800">Error loading posts</h3>
              <div class="mt-2 text-sm text-red-700">{{ error }}</div>
            </div>
          </div>
        </div>

        <!-- Loading State -->
        <div *ngIf="loading" class="text-center py-8">
          <div class="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-blue-500"></div>
          <p class="mt-2 text-gray-600">Loading posts...</p>
        </div>

        <!-- Posts List -->
        <div *ngIf="!loading" class="space-y-6">
          <div *ngFor="let post of posts" class="card">
            <div class="flex items-start justify-between">
              <div class="flex-1">
                <div class="flex items-center mb-2">
                  <span 
                    *ngIf="post.published" 
                    class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800"
                  >
                    Published
                  </span>
                  <span 
                    *ngIf="!post.published" 
                    class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-yellow-100 text-yellow-800"
                  >
                    Draft
                  </span>
                </div>
                
                <h3 class="text-lg font-semibold text-gray-900 mb-2">
                  {{ post.title }}
                </h3>
                
                <p class="text-gray-600 mb-4 line-clamp-3">
                  {{ post.content }}
                </p>
                
                <div class="flex items-center text-sm text-gray-500">
                  <span>By {{ getUserName(post) }}</span>
                  <span class="mx-2">•</span>
                  <span>{{ formatDate(post.createdAt) }}</span>
                </div>
              </div>
              
              <div class="ml-4 flex-shrink-0 flex space-x-2">
                <a 
                  [routerLink]="['/posts', post.id]"
                  class="inline-flex items-center px-3 py-1 border border-transparent text-sm font-medium rounded-md text-primary-600 bg-primary-50 hover:bg-primary-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500"
                >
                  <svg class="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"></path>
                  </svg>
                  View Post
                </a>
                <button 
                  (click)="openEditDialog(post)"
                  class="text-blue-600 hover:text-blue-900 text-sm font-medium"
                >
                  Edit
                </button>
                <button 
                  (click)="deletePostConfirm(post)"
                  class="text-red-600 hover:text-red-900 text-sm font-medium"
                >
                  Delete
                </button>
              </div>
            </div>
          </div>

          <!-- Empty State -->
          <div *ngIf="posts.length === 0" class="text-center py-12">
            <div class="mx-auto h-12 w-12 text-gray-400">
              <svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
              </svg>
            </div>
            <h3 class="mt-2 text-sm font-medium text-gray-900">No posts</h3>
            <p class="mt-1 text-sm text-gray-500">Get started by creating a new post.</p>
            <div class="mt-6">
              <button (click)="openCreateDialog()" class="btn-primary">
                <svg class="-ml-1 mr-2 h-5 w-5" fill="currentColor" viewBox="0 0 20 20">
                  <path fill-rule="evenodd" d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" clip-rule="evenodd"></path>
                </svg>
                New Post
              </button>
            </div>
          </div>
        </div>

        <!-- Create/Edit Dialog -->
        <div *ngIf="showDialog" class="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full z-50">
          <div class="relative top-20 mx-auto p-5 border w-96 shadow-lg rounded-md bg-white">
            <div class="mt-3">
              <h3 class="text-lg font-medium text-gray-900 mb-4">
                {{ isEditing ? 'Edit Post' : 'Create New Post' }}
              </h3>
              
              <form (ngSubmit)="submitPostForm()">
                <div class="mb-4">
                  <label class="block text-sm font-medium text-gray-700 mb-2">
                    Title *
                  </label>
                  <input
                    type="text"
                    required
                    [(ngModel)]="postForm.title"
                    name="title"
                    class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="Enter post title"
                  />
                </div>

                <div class="mb-4">
                  <label class="block text-sm font-medium text-gray-700 mb-2">
                    Content *
                  </label>
                  <textarea
                    required
                    [(ngModel)]="postForm.content"
                    name="content"
                    rows="6"
                    class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="Enter post content"
                  ></textarea>
                </div>

                <div class="mb-6">
                  <label class="flex items-center">
                    <input
                      type="checkbox"
                      [(ngModel)]="postForm.published"
                      name="published"
                      class="rounded border-gray-300 text-blue-600 shadow-sm focus:border-blue-300 focus:ring focus:ring-blue-200 focus:ring-opacity-50"
                    />
                    <span class="ml-2 text-sm text-gray-700">Publish immediately</span>
                  </label>
                </div>

                <div class="flex justify-end space-x-3">
                  <button
                    type="button"
                    (click)="closeDialog()"
                    class="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-100 border border-gray-300 rounded-md hover:bg-gray-200"
                    [disabled]="submitting"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    class="px-4 py-2 text-sm font-medium text-white bg-blue-600 border border-transparent rounded-md hover:bg-blue-700 disabled:opacity-50"
                    [disabled]="submitting"
                  >
                    {{ submitting ? 'Saving...' : (isEditing ? 'Update Post' : 'Create Post') }}
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .card {
      @apply bg-white overflow-hidden shadow rounded-lg p-6;
    }
    .btn-primary {
      @apply inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700;
    }
    .space-y-6 > * + * {
      margin-top: 1.5rem;
    }
    .line-clamp-3 {
      display: -webkit-box;
      -webkit-line-clamp: 3;
      -webkit-box-orient: vertical;
      overflow: hidden;
    }
  `]
})
export class PostsComponent implements OnInit {
  posts: Post[] = [];
  loading = true;
  error = '';
  showDialog = false;
  isEditing = false;
  editingPost: Post | null = null;
  submitting = false;

  postForm: PostForm = {
    title: '',
    content: '',
    published: false
  };

  constructor(private graphqlClient: GraphQLClientService) {}

  ngOnInit() {
    console.log('PostsComponent initialized');
    this.loadPosts();
  }

  async loadPosts() {
    console.log('=== LOADING POSTS ===');
    this.loading = true;
    this.error = '';
    
    try {
      console.log('1. About to call GraphQL client...');
      console.log('2. Query:', listPosts);
      
      const result = await this.graphqlClient.query(listPosts, {});
      console.log('3. Raw GraphQL result:', JSON.stringify(result, null, 2));
      
      if (result.data && result.data.listPosts) {
        this.posts = result.data.listPosts;
        console.log('4. Successfully loaded posts:', this.posts.length, 'posts');
        console.log('5. Posts data:', this.posts);
      } else {
        console.warn('4. No posts data in result structure:', result);
        this.posts = [];
      }
    } catch (err: any) {
      this.error = err?.message || 'Failed to load posts';
      console.error('4. Error loading posts:', err);
      console.error('5. Error details:', {
        message: err?.message,
        stack: err?.stack,
        name: err?.name
      });
      this.posts = [];
    } finally {
      this.loading = false;
      console.log('6. Loading complete. Posts count:', this.posts.length);
      console.log('=== END LOADING POSTS ===');
    }
  }

  formatDate(dateString: string): string {
    return new Date(dateString).toLocaleDateString();
  }

  getUserName(post: Post): string {
    return post.user?.name || 'Unknown User';
  }

  openCreateDialog() {
    this.isEditing = false;
    this.editingPost = null;
    this.postForm = {
      title: '',
      content: '',
      published: false
    };
    this.showDialog = true;
  }

  openEditDialog(post: Post) {
    this.isEditing = true;
    this.editingPost = post;
    this.postForm = {
      title: post.title,
      content: post.content,
      published: post.published
    };
    this.showDialog = true;
  }

  closeDialog() {
    this.showDialog = false;
    this.isEditing = false;
    this.editingPost = null;
    this.submitting = false;
  }

  async submitPostForm() {
    if (this.submitting) return;
    
    this.submitting = true;
    
    try {
      if (this.isEditing && this.editingPost) {
        // Update existing post
        const result = await this.graphqlClient.mutate(updatePost, {
          input: {
            id: this.editingPost.id,
            title: this.postForm.title,
            content: this.postForm.content,
            published: this.postForm.published
          }
        });
        
        console.log('Update post result:', result);
      } else {
        // Create new post
        const result = await this.graphqlClient.mutate(createPost, {
          input: {
            title: this.postForm.title,
            content: this.postForm.content,
            published: this.postForm.published
          }
        });
        
        console.log('Create post result:', result);
      }
      
      this.closeDialog();
      await this.loadPosts(); // Refresh the list
    } catch (err: any) {
      this.error = err?.message || 'Failed to save post';
      console.error('Error saving post:', err);
      alert('Failed to save post: ' + (err?.message || 'Unknown error'));
    } finally {
      this.submitting = false;
    }
  }

  async deletePostConfirm(post: Post) {
    if (!confirm(`Are you sure you want to delete "${post.title}"?`)) {
      return;
    }
    
    try {
      const result = await this.graphqlClient.mutate(deletePost, {
        input: { id: post.id }
      });
      
      console.log('Delete post result:', result);
      await this.loadPosts(); // Refresh the list
    } catch (err: any) {
      this.error = err?.message || 'Failed to delete post';
      console.error('Error deleting post:', err);
      alert('Failed to delete post: ' + (err?.message || 'Unknown error'));
    }
  }
}
