// frontend/angular/src/app/views/posts/posts.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';

interface Post {
  id: string;
  title: string;
  content: string;
  published: boolean;
  userId: string;
  createdAt: string;
}

interface User {
  id: string;
  name: string;
}

@Component({
  selector: 'app-posts',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="min-h-screen bg-gray-50 py-8">
      <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <!-- Header -->
        <div class="mb-8">
          <h1 class="text-3xl font-bold text-gray-900">Posts</h1>
          <p class="mt-2 text-gray-600">Manage your blog posts</p>
        </div>

        <!-- Loading State -->
        <div *ngIf="loading" class="text-center py-8">
          <div class="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-blue-500"></div>
          <p class="mt-2 text-gray-600">Loading posts...</p>
        </div>

        <!-- Posts List -->
        <div *ngIf="!loading" class="space-y-6">
          <div *ngFor="let post of posts" class="card">
            <div class="flex items-start justify-between">
              <div class="flex-1">
                <div class="flex items-center mb-2">
                  <span 
                    *ngIf="post.published" 
                    class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800"
                  >
                    Published
                  </span>
                  <span 
                    *ngIf="!post.published" 
                    class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-yellow-100 text-yellow-800"
                  >
                    Draft
                  </span>
                </div>
                
                <h3 class="text-lg font-semibold text-gray-900 mb-2">
                  {{ post.title }}
                </h3>
                
                <p class="text-gray-600 mb-4 line-clamp-3">
                  {{ post.content }}
                </p>
                
                <div class="flex items-center text-sm text-gray-500">
                  <span>By {{ getUserName(post.userId) }}</span>
                  <span class="mx-2">•</span>
                  <span>{{ formatDate(post.createdAt) }}</span>
                </div>
              </div>
              
              <div class="ml-4 flex-shrink-0">
                <button class="text-blue-600 hover:text-blue-900 text-sm font-medium">
                  Edit
                </button>
              </div>
            </div>
          </div>

          <!-- Empty State -->
          <div *ngIf="posts.length === 0" class="text-center py-12">
            <div class="mx-auto h-12 w-12 text-gray-400">
              <svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
              </svg>
            </div>
            <h3 class="mt-2 text-sm font-medium text-gray-900">No posts</h3>
            <p class="mt-1 text-sm text-gray-500">Get started by creating a new post.</p>
            <div class="mt-6">
              <button class="btn-primary">
                <svg class="-ml-1 mr-2 h-5 w-5" fill="currentColor" viewBox="0 0 20 20">
                  <path fill-rule="evenodd" d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" clip-rule="evenodd"></path>
                </svg>
                New Post
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .card {
      @apply bg-white overflow-hidden shadow rounded-lg p-6;
    }
    .btn-primary {
      @apply inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700;
    }
    .space-y-6 > * + * {
      margin-top: 1.5rem;
    }
    .line-clamp-3 {
      display: -webkit-box;
      -webkit-line-clamp: 3;
      -webkit-box-orient: vertical;
      overflow: hidden;
    }
  `]
})
export class PostsComponent implements OnInit {
  posts: Post[] = [];
  users: User[] = [];
  loading = true;

  ngOnInit() {
    this.loadPosts();
  }

  formatDate(dateString: string): string {
    return new Date(dateString).toLocaleDateString();
  }

  getUserName(userId: string): string {
    const user = this.users.find(u => u.id === userId);
    return user ? user.name : 'Unknown User';
  }

  private async loadPosts() {
    try {
      // TODO: Replace with actual GraphQL queries
      // Simulate API call
      await new Promise(resolve => setTimeout(resolve, 1000));
      
      this.users = [
        { id: '1', name: 'John Doe' },
        { id: '2', name: 'Jane Smith' },
        { id: '3', name: 'Bob Johnson' }
      ];

      this.posts = [
        {
          id: '1',
          title: 'Getting Started with AWS Application Accelerator',
          content: 'Learn how to build scalable applications using our model-driven framework. This comprehensive guide covers everything from setup to deployment, including best practices for GraphQL APIs, authentication, and CI/CD pipelines.',
          published: true,
          userId: '1',
          createdAt: '2024-01-15'
        },
        {
          id: '2',
          title: 'Building Real-time Applications with GraphQL Subscriptions',
          content: 'Discover how to implement real-time features in your applications using GraphQL subscriptions. We\'ll cover subscription setup, client-side implementation, and performance optimization techniques.',
          published: true,
          userId: '2',
          createdAt: '2024-01-14'
        },
        {
          id: '3',
          title: 'Advanced Security Patterns in Serverless Applications',
          content: 'Explore advanced security patterns including owner-based access control, group-based authorization, and field-level security. Learn how to implement these patterns in your AWS serverless applications.',
          published: false,
          userId: '3',
          createdAt: '2024-01-13'
        }
      ];
      
      this.loading = false;
    } catch (error) {
      console.error('Error loading posts:', error);
      this.loading = false;
    }
  }
}

// frontend/src/views/Posts.vue
<template>
  <div class="p-6">
    <div class="mb-8">
      <h1 class="text-3xl font-bold text-gray-900">Posts</h1>
      <p class="text-gray-600 mt-2">Manage your application posts</p>
    </div>

    <!-- Loading State -->
    <div v-if="loading" class="flex justify-center items-center py-12">
      <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-primary-600"></div>
    </div>

    <!-- Posts Grid -->
    <div v-else>
      <div class="flex justify-between items-center mb-6">
        <h2 class="text-xl font-semibold text-gray-900">All Posts</h2>
        <button class="btn-primary">
          Create Post
        </button>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <div v-for="post in posts" :key="post.id" class="card hover:shadow-lg transition-shadow">
          <div class="flex items-center justify-between mb-3">
            <span
              :class="[
                'px-2 py-1 text-xs font-medium rounded-full',
                post.published
                  ? 'bg-green-100 text-green-800'
                  : 'bg-yellow-100 text-yellow-800'
              ]"
            >
              {{ post.published ? 'Published' : 'Draft' }}
            </span>
            <div class="flex space-x-2">
              <button class="text-gray-400 hover:text-gray-600">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"></path>
                </svg>
              </button>
              <button class="text-gray-400 hover:text-red-600">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path>
                </svg>
              </button>
            </div>
          </div>
          
          <h3 class="text-lg font-semibold text-gray-900 mb-2">{{ post.title }}</h3>
          <p class="text-gray-600 text-sm mb-4 line-clamp-3">{{ post.content }}</p>
          
          <div class="flex items-center justify-between text-sm text-gray-500">
            <span>By {{ getUserName(post.userId) }}</span>
            <span>{{ formatDate(post.createdAt) }}</span>
          </div>
        </div>
      </div>

      <!-- Empty State -->
      <div v-if="posts.length === 0" class="text-center py-12">
        <svg class="mx-auto h-12 w-12 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 20H5a2 2 0 01-2-2V6a2 2 0 012-2h10a2 2 0 012 2v1m2 13a2 2 0 01-2-2V7m2 13a2 2 0 002-2V9a2 2 0 00-2-2h-2m-4-3H9M7 16h6M7 8h6v4H7V8z"></path>
        </svg>
        <h3 class="mt-2 text-sm font-medium text-gray-900">No posts</h3>
        <p class="mt-1 text-sm text-gray-500">Get started by creating a new post.</p>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { API } from 'aws-amplify'
import { listPosts } from '../graphql/queries'

const loading = ref(true)
const posts = ref([])
const users = ref(new Map())

const formatDate = (dateString: string) => {
  return new Date(dateString).toLocaleDateString()
}

const getUserName = (userId: string) => {
  return users.value.get(userId) || 'Unknown User'
}

const loadPosts = async () => {
  try {
    loading.value = true
    const result = await API.graphql({
      query: listPosts
    })
    posts.value = result.data.listPosts || []
  } catch (error) {
    console.error('Error loading posts:', error)
    // Use mock data for demonstration
    posts.value = [
      {
        id: 'post-1',
        title: 'Getting Started with AWS CDK',
        content: 'AWS CDK is a powerful tool for defining cloud infrastructure using familiar programming languages. In this post, we\'ll explore how to get started with CDK and build your first stack.',
        userId: 'user-1',
        published: true,
        createdAt: '2024-01-15T10:00:00Z'
      },
      {
        id: 'post-2',
        title: 'Building Scalable APIs with AppSync',
        content: 'AWS AppSync provides a managed GraphQL service that makes it easy to build scalable APIs. Learn how to create real-time applications with subscriptions and offline support.',
        userId: 'user-1',
        published: true,
        createdAt: '2024-01-20T14:30:00Z'
      },
      {
        id: 'post-3',
        title: 'User Experience Best Practices',
        content: 'Creating great user experiences requires understanding your users and their needs. This post covers essential UX principles and how to apply them in your applications.',
        userId: 'user-2',
        published: false,
        createdAt: '2024-01-25T09:15:00Z'
      }
    ]
    
    // Mock user data
    users.value.set('user-1', 'John Doe')
    users.value.set('user-2', 'Jane Smith')
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  loadPosts()
})
</script>

<style scoped>
.line-clamp-3 {
  display: -webkit-box;
  -webkit-line-clamp: 3;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
</style>
