// frontend/react/src/views/admin/AnalyticsDashboard.tsx
import React, { useState, useEffect, useMemo } from 'react';
import { useAnalytics } from '../../services/analytics';
import { apolloClient } from '../../graphql/client';
import { gql } from '@apollo/client';

interface LogEntry {
  id: string;
  userId: string;
  action: string;
  component: string;
  level: string;
  metadata?: any;
  createdAt: string;
  user?: {
    id: string;
    name: string;
    email: string;
  };
}

const AnalyticsDashboard: React.FC = () => {
  const { trackAction, trackError } = useAnalytics('analytics-dashboard');
  
  const [logs, setLogs] = useState<LogEntry[]>([]);
  const [filters, setFilters] = useState({
    search: '',
    component: '',
    action: '',
    level: '',
    dateFrom: '',
    dateTo: ''
  });
  const [currentPage, setCurrentPage] = useState(1);
  const pageSize = 50;

  const LOGS_QUERY = gql`
    query GetLogs($limit: Int, $nextToken: String) {
      listLogs(limit: $limit, nextToken: $nextToken) {
        items {
          id
          userId
          action
          component
          level
          metadata
          createdAt
          user {
            id
            name
            email
          }
        }
        nextToken
      }
    }
  `;

  const LOGS_SUBSCRIPTION = gql`
    subscription OnLogCreated {
      onCreateLog {
        id
        userId
        action
        component
        level
        metadata
        createdAt
        user {
          id
          name
          email
        }
      }
    }
  `;

  const filteredLogs = useMemo(() => {
    let filtered = logs;

    if (filters.search) {
      const search = filters.search.toLowerCase();
      filtered = filtered.filter(log => 
        log.component.toLowerCase().includes(search) ||
        log.action.toLowerCase().includes(search) ||
        log.user?.name?.toLowerCase().includes(search)
      );
    }

    if (filters.component) {
      filtered = filtered.filter(log => log.component === filters.component);
    }

    if (filters.action) {
      filtered = filtered.filter(log => log.action === filters.action);
    }

    if (filters.level) {
      filtered = filtered.filter(log => log.level === filters.level);
    }

    if (filters.dateFrom) {
      const fromDate = new Date(filters.dateFrom);
      filtered = filtered.filter(log => new Date(log.createdAt) >= fromDate);
    }

    if (filters.dateTo) {
      const toDate = new Date(filters.dateTo);
      filtered = filtered.filter(log => new Date(log.createdAt) <= toDate);
    }

    return filtered.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
  }, [logs, filters]);

  const paginatedLogs = useMemo(() => {
    const start = (currentPage - 1) * pageSize;
    const end = start + pageSize;
    return filteredLogs.slice(start, end);
  }, [filteredLogs, currentPage]);

  const totalPages = useMemo(() => {
    return Math.ceil(filteredLogs.length / pageSize);
  }, [filteredLogs.length]);

  const uniqueComponents = useMemo(() => {
    return [...new Set(logs.map(log => log.component))].sort();
  }, [logs]);

  const uniqueActions = useMemo(() => {
    return [...new Set(logs.map(log => log.action))].sort();
  }, [logs]);

  useEffect(() => {
    loadLogs();
    setupSubscription();
  }, []);

  const loadLogs = async () => {
    try {
      const result = await apolloClient.query({
        query: LOGS_QUERY,
        variables: { limit: 1000 },
        fetchPolicy: 'network-only'
      });
      
      setLogs(result.data.listLogs.items);
      trackAction('logs-loaded', { count: result.data.listLogs.items.length });
    } catch (error) {
      trackError('failed-to-load-logs', { error: error.message });
    }
  };

  const setupSubscription = () => {
    try {
      const subscription = apolloClient.subscribe({
        query: LOGS_SUBSCRIPTION
      }).subscribe({
        next: ({ data }) => {
          setLogs(prevLogs => [data.onCreateLog, ...prevLogs]);
          trackAction('real-time-log-received');
        },
        error: (error) => {
          trackError('subscription-error', { error: error.message });
        }
      });

      return () => subscription.unsubscribe();
    } catch (error) {
      trackError('failed-to-setup-subscription', { error: error.message });
    }
  };

  const clearFilters = () => {
    setFilters({
      search: '',
      component: '',
      action: '',
      level: '',
      dateFrom: '',
      dateTo: ''
    });
    setCurrentPage(1);
    trackAction('filters-cleared');
  };

  const exportLogs = () => {
    try {
      const csvData = filteredLogs.map(log => ({
        timestamp: log.createdAt,
        user: log.user?.name || log.userId,
        component: log.component,
        action: log.action,
        level: log.level,
        metadata: JSON.stringify(log.metadata || {})
      }));

      const csv = [
        Object.keys(csvData[0]).join(','),
        ...csvData.map(row => Object.values(row).map(val => `"${val}"`).join(','))
      ].join('\n');

      const blob = new Blob([csv], { type: 'text/csv' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `analytics-logs-${new Date().toISOString().split('T')[0]}.csv`;
      a.click();
      URL.revokeObjectURL(url);

      trackAction('logs-exported', { count: csvData.length });
    } catch (error) {
      trackError('export-failed', { error: error.message });
    }
  };

  const formatTimestamp = (timestamp: string) => {
    return new Date(timestamp).toLocaleString();
  };

  return (
    <div className="analytics-dashboard">
      <div className="dashboard-controls">
        <div className="filters">
          <input 
            value={filters.search}
            onChange={(e) => setFilters({...filters, search: e.target.value})}
            placeholder="Search logs..." 
            className="search-input"
          />
          
          <select 
            value={filters.component} 
            onChange={(e) => setFilters({...filters, component: e.target.value})}
          >
            <option value="">All Components</option>
            {uniqueComponents.map(component => (
              <option key={component} value={component}>{component}</option>
            ))}
          </select>

          <select 
            value={filters.action} 
            onChange={(e) => setFilters({...filters, action: e.target.value})}
          >
            <option value="">All Actions</option>
            {uniqueActions.map(action => (
              <option key={action} value={action}>{action}</option>
            ))}
          </select>

          <select 
            value={filters.level} 
            onChange={(e) => setFilters({...filters, level: e.target.value})}
          >
            <option value="">All Levels</option>
            <option value="info">Info</option>
            <option value="warn">Warning</option>
            <option value="error">Error</option>
          </select>

          <input 
            value={filters.dateFrom}
            onChange={(e) => setFilters({...filters, dateFrom: e.target.value})}
            type="datetime-local" 
            className="date-input"
          />
          
          <input 
            value={filters.dateTo}
            onChange={(e) => setFilters({...filters, dateTo: e.target.value})}
            type="datetime-local" 
            className="date-input"
          />

          <button onClick={clearFilters} className="btn-secondary">Clear Filters</button>
          <button onClick={exportLogs} className="btn-primary">Export CSV</button>
        </div>
      </div>

      <div className="analytics-content">
        <div className="charts-section">
          <div className="chart-container">
            <h3>Activity Timeline</h3>
            <div className="chart-placeholder">Chart would be rendered here</div>
          </div>
          
          <div className="chart-container">
            <h3>Action Distribution</h3>
            <div className="chart-placeholder">Chart would be rendered here</div>
          </div>
          
          <div className="chart-container">
            <h3>Component Usage</h3>
            <div className="chart-placeholder">Chart would be rendered here</div>
          </div>
          
          <div className="chart-container">
            <h3>Error Rates</h3>
            <div className="chart-placeholder">Chart would be rendered here</div>
          </div>
        </div>

        <div className="logs-section">
          <div className="logs-header">
            <h3>Raw Logs ({filteredLogs.length})</h3>
            <div className="pagination">
              <button 
                onClick={() => setCurrentPage(currentPage - 1)} 
                disabled={currentPage <= 1}
                className="btn-secondary"
              >
                Previous
              </button>
              <span>Page {currentPage} of {totalPages}</span>
              <button 
                onClick={() => setCurrentPage(currentPage + 1)} 
                disabled={currentPage >= totalPages}
                className="btn-secondary"
              >
                Next
              </button>
            </div>
          </div>

          <div className="logs-table">
            <table>
              <thead>
                <tr>
                  <th>Timestamp</th>
                  <th>User</th>
                  <th>Component</th>
                  <th>Action</th>
                  <th>Level</th>
                  <th>Metadata</th>
                </tr>
              </thead>
              <tbody>
                {paginatedLogs.map(log => (
                  <tr key={log.id} className={`log-row ${log.level}`}>
                    <td>{formatTimestamp(log.createdAt)}</td>
                    <td>{log.user?.name || log.userId}</td>
                    <td>{log.component}</td>
                    <td>{log.action}</td>
                    <td>
                      <span className={`level-badge ${log.level}`}>{log.level}</span>
                    </td>
                    <td>
                      {log.metadata && (
                        <details>
                          <summary>View</summary>
                          <pre>{JSON.stringify(log.metadata, null, 2)}</pre>
                        </details>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AnalyticsDashboard;

// frontend/angular/src/app/views/admin/analytics-dashboard.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { AnalyticsService } from '../../services/analytics.service';
import { GraphQLClientService } from '../../graphql/client';

interface LogEntry {
  id: string;
  userId: string;
  action: string;
  component: string;
  level: string;
  metadata?: any;
  createdAt: string;
  user?: {
    id: string;
    name: string;
    email: string;
  };
}

@Component({
  selector: 'app-analytics-dashboard',
  templateUrl: './analytics-dashboard.component.html',
  styleUrls: ['./analytics-dashboard.component.css']
})
export class AnalyticsDashboardComponent implements OnInit, OnDestroy {
  logs: LogEntry[] = [];
  filters = {
    search: '',
    component: '',
    action: '',
    level: '',
    dateFrom: '',
    dateTo: ''
  };
  currentPage = 1;
  pageSize = 50;
  subscription: any = null;

  constructor(
    private analyticsService: AnalyticsService,
    private graphqlClient: GraphQLClientService
  ) {}

  ngOnInit(): void {
    this.analyticsService.trackView('analytics-dashboard');
    this.loadLogs();
    this.setupSubscription();
  }

  ngOnDestroy(): void {
    if (this.subscription) {
      this.subscription.unsubscribe();
    }
  }

  get filteredLogs(): LogEntry[] {
    let filtered = this.logs;

    if (this.filters.search) {
      const search = this.filters.search.toLowerCase();
      filtered = filtered.filter(log => 
        log.component.toLowerCase().includes(search) ||
        log.action.toLowerCase().includes(search) ||
        log.user?.name?.toLowerCase().includes(search)
      );
    }

    if (this.filters.component) {
      filtered = filtered.filter(log => log.component === this.filters.component);
    }

    if (this.filters.action) {
      filtered = filtered.filter(log => log.action === this.filters.action);
    }

    if (this.filters.level) {
      filtered = filtered.filter(log => log.level === this.filters.level);
    }

    if (this.filters.dateFrom) {
      const fromDate = new Date(this.filters.dateFrom);
      filtered = filtered.filter(log => new Date(log.createdAt) >= fromDate);
    }

    if (this.filters.dateTo) {
      const toDate = new Date(this.filters.dateTo);
      filtered = filtered.filter(log => new Date(log.createdAt) <= toDate);
    }

    return filtered.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
  }

  get paginatedLogs(): LogEntry[] {
    const start = (this.currentPage - 1) * this.pageSize;
    const end = start + this.pageSize;
    return this.filteredLogs.slice(start, end);
  }

  get totalPages(): number {
    return Math.ceil(this.filteredLogs.length / this.pageSize);
  }

  get uniqueComponents(): string[] {
    return [...new Set(this.logs.map(log => log.component))].sort();
  }

  get uniqueActions(): string[] {
    return [...new Set(this.logs.map(log => log.action))].sort();
  }

  async loadLogs(): Promise<void> {
    try {
      const query = `
        query GetLogs($limit: Int, $nextToken: String) {
          listLogs(limit: $limit, nextToken: $nextToken) {
            items {
              id
              userId
              action
              component
              level
              metadata
              createdAt
              user {
                id
                name
                email
              }
            }
            nextToken
          }
        }
      `;

      const result = await this.graphqlClient.query(query, { limit: 1000 });
      this.logs = result.data.listLogs.items;
      
      this.analyticsService.trackAction('logs-loaded', 'analytics-dashboard', { count: this.logs.length });
    } catch (error) {
      this.analyticsService.trackError('failed-to-load-logs', 'analytics-dashboard', { error: error.message });
    }
  }

  private setupSubscription(): void {
    try {
      // In a real implementation, this would set up a WebSocket subscription
      // For now, we'll simulate it with periodic polling
      this.subscription = setInterval(() => {
        this.loadLogs();
      }, 30000); // Refresh every 30 seconds

      this.analyticsService.trackAction('subscription-setup', 'analytics-dashboard');
    } catch (error) {
      this.analyticsService.trackError('failed-to-setup-subscription', 'analytics-dashboard', { error: error.message });
    }
  }

  clearFilters(): void {
    this.filters = {
      search: '',
      component: '',
      action: '',
      level: '',
      dateFrom: '',
      dateTo: ''
    };
    this.currentPage = 1;
    this.analyticsService.trackAction('filters-cleared', 'analytics-dashboard');
  }

  exportLogs(): void {
    try {
      const csvData = this.filteredLogs.map(log => ({
        timestamp: log.createdAt,
        user: log.user?.name || log.userId,
        component: log.component,
        action: log.action,
        level: log.level,
        metadata: JSON.stringify(log.metadata || {})
      }));

      const csv = [
        Object.keys(csvData[0]).join(','),
        ...csvData.map(row => Object.values(row).map(val => `"${val}"`).join(','))
      ].join('\n');

      const blob = new Blob([csv], { type: 'text/csv' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `analytics-logs-${new Date().toISOString().split('T')[0]}.csv`;
      a.click();
      URL.revokeObjectURL(url);

      this.analyticsService.trackAction('logs-exported', 'analytics-dashboard', { count: csvData.length });
    } catch (error) {
      this.analyticsService.trackError('export-failed', 'analytics-dashboard', { error: error.message });
    }
  }

  formatTimestamp(timestamp: string): string {
    return new Date(timestamp).toLocaleString();
  }

  previousPage(): void {
    if (this.currentPage > 1) {
      this.currentPage--;
    }
  }

  nextPage(): void {
    if (this.currentPage < this.totalPages) {
      this.currentPage++;
    }
  }

  onSearchChange(): void {
    this.analyticsService.trackAction('search-logs', 'analytics-dashboard');
  }

  onFilterChange(filterType: string): void {
    this.analyticsService.trackAction('filter-' + filterType, 'analytics-dashboard');
  }
}
<div class="analytics-dashboard">
  <div class="dashboard-controls">
    <div class="filters">
      <input 
        [(ngModel)]="filters.search"
        (input)="onSearchChange()"
        placeholder="Search logs..." 
        class="search-input"
      />
      
      <select [(ngModel)]="filters.component" (change)="onFilterChange('component')">
        <option value="">All Components</option>
        <option *ngFor="let component of uniqueComponents" [value]="component">
          {{ component }}
        </option>
      </select>

      <select [(ngModel)]="filters.action" (change)="onFilterChange('action')">
        <option value="">All Actions</option>
        <option *ngFor="let action of uniqueActions" [value]="action">
          {{ action }}
        </option>
      </select>

      <select [(ngModel)]="filters.level" (change)="onFilterChange('level')">
        <option value="">All Levels</option>
        <option value="info">Info</option>
        <option value="warn">Warning</option>
        <option value="error">Error</option>
      </select>

      <input 
        [(ngModel)]="filters.dateFrom"
        (change)="onFilterChange('date-from')"
        type="datetime-local" 
        class="date-input"
      />
      
      <input 
        [(ngModel)]="filters.dateTo"
        (change)="onFilterChange('date-to')"
        type="datetime-local" 
        class="date-input"
      />

      <button (click)="clearFilters()" class="btn-secondary">Clear Filters</button>
      <button (click)="exportLogs()" class="btn-primary">Export CSV</button>
    </div>
  </div>

  <div class="analytics-content">
    <div class="charts-section">
      <div class="chart-container">
        <h3>Activity Timeline</h3>
        <div class="chart-placeholder">Chart would be rendered here</div>
      </div>
      
      <div class="chart-container">
        <h3>Action Distribution</h3>
        <div class="chart-placeholder">Chart would be rendered here</div>
      </div>
      
      <div class="chart-container">
        <h3>Component Usage</h3>
        <div class="chart-placeholder">Chart would be rendered here</div>
      </div>
      
      <div class="chart-container">
        <h3>Error Rates</h3>
        <div class="chart-placeholder">Chart would be rendered here</div>
      </div>
    </div>

    <div class="logs-section">
      <div class="logs-header">
        <h3>Raw Logs ({{ filteredLogs.length }})</h3>
        <div class="pagination">
          <button 
            (click)="previousPage()" 
            [disabled]="currentPage <= 1"
            class="btn-secondary"
          >
            Previous
          </button>
          <span>Page {{ currentPage }} of {{ totalPages }}</span>
          <button 
            (click)="nextPage()" 
            [disabled]="currentPage >= totalPages"
            class="btn-secondary"
          >
            Next
          </button>
        </div>
      </div>

      <div class="logs-table">
        <table>
          <thead>
            <tr>
              <th>Timestamp</th>
              <th>User</th>
              <th>Component</th>
              <th>Action</th>
              <th>Level</th>
              <th>Metadata</th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let log of paginatedLogs" [class]="'log-row ' + log.level">
              <td>{{ formatTimestamp(log.createdAt) }}</td>
              <td>{{ log.user?.name || log.userId }}</td>
              <td>{{ log.component }}</td>
              <td>{{ log.action }}</td>
              <td>
                <span [class]="'level-badge ' + log.level">{{ log.level }}</span>
              </td>
              <td>
                <details *ngIf="log.metadata">
                  <summary>View</summary>
                  <pre>{{ log.metadata | json }}</pre>
                </details>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
