// frontend/react/src/views/admin/DataManagement.tsx
import React, { useState, useEffect, useMemo } from 'react';
import { useAnalytics } from '../../services/analytics';
import { apolloClient } from '../../graphql/client';
import { gql } from '@apollo/client';

const DataManagement: React.FC = () => {
  const { trackAction, trackError } = useAnalytics('data-management');
  
  const availableModels = ['User', 'Post', 'Setting', 'Log'];
  const [selectedModel, setSelectedModel] = useState('');
  const [modelData, setModelData] = useState<any[]>([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedRecords, setSelectedRecords] = useState<string[]>([]);
  const [sortField, setSortField] = useState('createdAt');
  const [sortDirection, setSortDirection] = useState<'asc' | 'desc'>('desc');
  const [currentPage, setCurrentPage] = useState(1);
  const [pageSize, setPageSize] = useState(25);
  const [exportFormat, setExportFormat] = useState<'CSV' | 'JSON'>('CSV');
  
  // Modals
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [showEditModal, setShowEditModal] = useState(false);
  const [formData, setFormData] = useState<any>({});
  const [editingRecord, setEditingRecord] = useState<any>(null);

  const modelFields = useMemo(() => {
    if (modelData.length === 0) return [];
    return Object.keys(modelData[0]).filter(key => key !== '__typename');
  }, [modelData]);

  const editableFields = useMemo(() => {
    return modelFields.filter(field => field !== 'id' && !field.includes('_local'));
  }, [modelFields]);

  const requiredFields = useMemo(() => {
    return ['name', 'email', 'title', 'key', 'type'].filter(field => 
      editableFields.includes(field)
    );
  }, [editableFields]);

  const filteredRecords = useMemo(() => {
    let filtered = modelData;

    if (searchQuery) {
      const query = searchQuery.toLowerCase();
      filtered = filtered.filter(record => 
        Object.values(record).some(value => 
          String(value).toLowerCase().includes(query)
        )
      );
    }

    // Sort
    filtered.sort((a, b) => {
      const aVal = a[sortField];
      const bVal = b[sortField];
      
      if (sortDirection === 'asc') {
        return aVal > bVal ? 1 : -1;
      } else {
        return aVal < bVal ? 1 : -1;
      }
    });

    return filtered;
  }, [modelData, searchQuery, sortField, sortDirection]);

  const paginatedRecords = useMemo(() => {
    const start = (currentPage - 1) * pageSize;
    const end = start + pageSize;
    return filteredRecords.slice(start, end);
  }, [filteredRecords, currentPage, pageSize]);

  const totalPages = useMemo(() => {
    return Math.ceil(filteredRecords.length / pageSize);
  }, [filteredRecords.length, pageSize]);

  const allSelected = useMemo(() => {
    return paginatedRecords.length > 0 && 
           selectedRecords.length === paginatedRecords.length;
  }, [paginatedRecords.length, selectedRecords.length]);

  useEffect(() => {
    trackAction('data-management-loaded');
  }, []);

  const getModelFields = (model: string): string => {
    const commonFields = 'id createdAt updatedAt';
    
    switch (model) {
      case 'User':
        return `${commonFields} userId name email role bio`;
      case 'Post':
        return `${commonFields} title content userId published`;
      case 'Setting':
        return `${commonFields} type key value entityId description isActive`;
      case 'Log':
        return `${commonFields} userId action component level metadata user { id name }`;
      default:
        return commonFields;
    }
  };

  const loadModelData = async () => {
    if (!selectedModel) return;

    try {
      const query = gql`
        query List${selectedModel}s {
          list${selectedModel}s {
            ${getModelFields(selectedModel)}
          }
        }
      `;

      const result = await apolloClient.query({
        query,
        fetchPolicy: 'network-only'
      });

      setModelData(result.data[`list${selectedModel}s`] || []);
      setSelectedRecords([]);
      setCurrentPage(1);
      
      trackAction('model-data-loaded', { 
        model: selectedModel, 
        count: result.data[`list${selectedModel}s`]?.length || 0
      });
    } catch (error) {
      trackError('failed-to-load-model-data', { 
        model: selectedModel, 
        error: error.message 
      });
    }
  };

  const refreshData = () => {
    loadModelData();
    trackAction('data-refreshed', { model: selectedModel });
  };

  const exportData = () => {
    try {
      const data = filteredRecords;
      
      if (exportFormat === 'CSV') {
        const csv = [
          modelFields.join(','),
          ...data.map(record => 
            modelFields.map(field => {
              const value = record[field];
              return typeof value === 'object' ? JSON.stringify(value) : value;
            }).map(val => `"${val}"`).join(',')
          )
        ].join('\n');

        const blob = new Blob([csv], { type: 'text/csv' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${selectedModel}-export-${new Date().toISOString().split('T')[0]}.csv`;
        a.click();
        URL.revokeObjectURL(url);
      } else {
        const json = JSON.stringify(data, null, 2);
        const blob = new Blob([json], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${selectedModel}-export-${new Date().toISOString().split('T')[0]}.json`;
        a.click();
        URL.revokeObjectURL(url);
      }

      trackAction('data-exported', { 
        model: selectedModel, 
        format: exportFormat,
        count: data.length 
      });
    } catch (error) {
      trackError('export-failed', { error: error.message });
    }
  };

  const toggleSelectAll = () => {
    if (allSelected) {
      setSelectedRecords([]);
    } else {
      setSelectedRecords(paginatedRecords.map(record => record.id));
    }
  };

  const sortBy = (field: string) => {
    if (sortField === field) {
      setSortDirection(sortDirection === 'asc' ? 'desc' : 'asc');
    } else {
      setSortField(field);
      setSortDirection('asc');
    }
    trackAction('data-sorted', { field, direction: sortDirection });
  };

  const editRecord = (record: any) => {
    setEditingRecord(record);
    setFormData({ ...record });
    setShowEditModal(true);
    trackAction('edit-record-opened', { model: selectedModel, id: record.id });
  };

  const deleteRecord = async (record: any) => {
    if (!window.confirm(`Are you sure you want to delete this ${selectedModel}?`)) {
      return;
    }

    try {
      const mutation = gql`
        mutation Delete${selectedModel}($input: Delete${selectedModel}Input!) {
          delete${selectedModel}(input: $input) {
            id
          }
        }
      `;

      await apolloClient.mutate({
        mutation,
        variables: { input: { id: record.id } }
      });

      await loadModelData();
      trackAction('record-deleted', { model: selectedModel, id: record.id });
    } catch (error) {
      trackError('delete-failed', { error: error.message });
    }
  };

  const impersonateUser = async (user: any) => {
    if (!window.confirm(`Impersonate user ${user.name}? This will log you in as this user.`)) {
      return;
    }

    try {
      trackAction('user-impersonation', { 
        targetUserId: user.id, 
        targetUserName: user.name 
      });
      
      window.location.href = '/';
    } catch (error) {
      trackError('impersonation-failed', { error: error.message });
    }
  };

  const formatTimestamp = (timestamp: string) => {
    return new Date(timestamp).toLocaleString();
  };

  return (
    <div className="data-management">
      <div className="management-header">
        <h2>Data Management</h2>
        <div className="model-selector">
          <select 
            value={selectedModel} 
            onChange={(e) => setSelectedModel(e.target.value)}
          >
            <option value="">Select Model</option>
            {availableModels.map(model => (
              <option key={model} value={model}>{model}</option>
            ))}
          </select>
          <button onClick={refreshData} className="btn-secondary">Refresh</button>
          <button 
            onClick={exportData} 
            className="btn-primary" 
            disabled={!selectedModel}
          >
            Export {exportFormat}
          </button>
          <select 
            value={exportFormat} 
            onChange={(e) => setExportFormat(e.target.value as 'CSV' | 'JSON')}
          >
            <option value="CSV">CSV</option>
            <option value="JSON">JSON</option>
          </select>
        </div>
      </div>

      {selectedModel && (
        <div className="model-management">
          <div className="actions-bar">
            <button 
              onClick={() => setShowCreateModal(true)} 
              className="btn-primary"
            >
              Create New {selectedModel}
            </button>
            <div className="search-bar">
              <input 
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Search records..." 
                className="search-input"
              />
            </div>
          </div>

          <div className="data-table">
            <table>
              <thead>
                <tr>
                  <th>
                    <input 
                      type="checkbox" 
                      onChange={toggleSelectAll}
                      checked={allSelected}
                    />
                  </th>
                  {modelFields.map(field => (
                    <th key={field} onClick={() => sortBy(field)}>
                      {field}
                      {sortField === field && (
                        <span>{sortDirection === 'asc' ? '↑' : '↓'}</span>
                      )}
                    </th>
                  ))}
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {paginatedRecords.map(record => (
                  <tr key={record.id}>
                    <td>
                      <input 
                        type="checkbox" 
                        value={record.id}
                        checked={selectedRecords.includes(record.id)}
                        onChange={(e) => {
                          if (e.target.checked) {
                            setSelectedRecords([...selectedRecords, record.id]);
                          } else {
                            setSelectedRecords(selectedRecords.filter(id => id !== record.id));
                          }
                        }}
                      />
                    </td>
                    {modelFields.map(field => (
                      <td key={field}>
                        {field.includes('At') ? (
                          <div className="timestamp">
                            {formatTimestamp(record[field])}
                          </div>
                        ) : typeof record[field] === 'object' ? (
                          <details>
                            <summary>Object</summary>
                            <pre>{JSON.stringify(record[field], null, 2)}</pre>
                          </details>
                        ) : (
                          record[field]
                        )}
                      </td>
                    ))}
                    <td className="actions">
                      <button 
                        onClick={() => editRecord(record)} 
                        className="btn-sm btn-secondary"
                      >
                        Edit
                      </button>
                      <button 
                        onClick={() => deleteRecord(record)} 
                        className="btn-sm btn-danger"
                      >
                        Delete
                      </button>
                      {selectedModel === 'User' && (
                        <button 
                          onClick={() => impersonateUser(record)}
                          className="btn-sm btn-warning"
                        >
                          Impersonate
                        </button>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div className="pagination">
            <button 
              onClick={() => setCurrentPage(currentPage - 1)} 
              disabled={currentPage <= 1}
              className="btn-secondary"
            >
              Previous
            </button>
            <span>Page {currentPage} of {totalPages}</span>
            <button 
              onClick={() => setCurrentPage(currentPage + 1)} 
              disabled={currentPage >= totalPages}
              className="btn-secondary"
            >
              Next
            </button>
            <select 
              value={pageSize} 
              onChange={(e) => {
                setPageSize(Number(e.target.value));
                setCurrentPage(1);
              }}
            >
              <option value="10">10 per page</option>
              <option value="25">25 per page</option>
              <option value="50">50 per page</option>
              <option value="100">100 per page</option>
            </select>
          </div>
        </div>
      )}
    </div>
  );
};

export default DataManagement;

// frontend/angular/src/app/views/admin/data-management.component.ts
import { Component, OnInit } from '@angular/core';
import { AnalyticsService } from '../../services/analytics.service';
import { GraphQLClientService } from '../../graphql/client';

@Component({
  selector: 'app-data-management',
  templateUrl: './data-management.component.html',
  styleUrls: ['./data-management.component.css']
})
export class DataManagementComponent implements OnInit {
  availableModels = ['User', 'Post', 'Setting', 'Log'];
  selectedModel = '';
  modelData: any[] = [];
  searchQuery = '';
  selectedRecords: string[] = [];
  sortField = 'createdAt';
  sortDirection: 'asc' | 'desc' = 'desc';
  currentPage = 1;
  pageSize = 25;
  exportFormat: 'CSV' | 'JSON' = 'CSV';

  // Modals
  showCreateModal = false;
  showEditModal = false;
  formData: any = {};
  editingRecord: any = null;

  constructor(
    private analyticsService: AnalyticsService,
    private graphqlClient: GraphQLClientService
  ) {}

  ngOnInit(): void {
    this.analyticsService.trackView('data-management');
  }

  get modelFields(): string[] {
    if (this.modelData.length === 0) return [];
    return Object.keys(this.modelData[0]).filter(key => key !== '__typename');
  }

  get editableFields(): string[] {
    return this.modelFields.filter(field => field !== 'id' && !field.includes('_local'));
  }

  get requiredFields(): string[] {
    return ['name', 'email', 'title', 'key', 'type'].filter(field => 
      this.editableFields.includes(field)
    );
  }

  get filteredRecords(): any[] {
    let filtered = this.modelData;

    if (this.searchQuery) {
      const query = this.searchQuery.toLowerCase();
      filtered = filtered.filter(record => 
        Object.values(record).some(value => 
          String(value).toLowerCase().includes(query)
        )
      );
    }

    // Sort
    filtered.sort((a, b) => {
      const aVal = a[this.sortField];
      const bVal = b[this.sortField];
      
      if (this.sortDirection === 'asc') {
        return aVal > bVal ? 1 : -1;
      } else {
        return aVal < bVal ? 1 : -1;
      }
    });

    return filtered;
  }

  get paginatedRecords(): any[] {
    const start = (this.currentPage - 1) * this.pageSize;
    const end = start + this.pageSize;
    return this.filteredRecords.slice(start, end);
  }

  get totalPages(): number {
    return Math.ceil(this.filteredRecords.length / this.pageSize);
  }

  get allSelected(): boolean {
    return this.paginatedRecords.length > 0 && 
           this.selectedRecords.length === this.paginatedRecords.length;
  }

  private getModelFields(model: string): string {
    const commonFields = 'id createdAt updatedAt';
    
    switch (model) {
      case 'User':
        return `${commonFields} userId name email role bio`;
      case 'Post':
        return `${commonFields} title content userId published`;
      case 'Setting':
        return `${commonFields} type key value entityId description isActive`;
      case 'Log':
        return `${commonFields} userId action component level metadata user { id name }`;
      default:
        return commonFields;
    }
  }

  async onModelChange(): Promise<void> {
    await this.loadModelData();
  }

  async loadModelData(): Promise<void> {
    if (!this.selectedModel) return;

    try {
      const query = `
        query List${this.selectedModel}s {
          list${this.selectedModel}s {
            ${this.getModelFields(this.selectedModel)}
          }
        }
      `;

      const result = await this.graphqlClient.query(query);
      this.modelData = result.data[`list${this.selectedModel}s`] || [];
      this.selectedRecords = [];
      this.currentPage = 1;
      
      this.analyticsService.trackAction('model-data-loaded', 'data-management', { 
        model: this.selectedModel, 
        count: this.modelData.length 
      });
    } catch (error) {
      this.analyticsService.trackError('failed-to-load-model-data', 'data-management', { 
        model: this.selectedModel, 
        error: error.message 
      });
    }
  }

  refreshData(): void {
    this.loadModelData();
    this.analyticsService.trackAction('data-refreshed', 'data-management', { model: this.selectedModel });
  }

  exportData(): void {
    try {
      const data = this.filteredRecords;
      
      if (this.exportFormat === 'CSV') {
        const csv = [
          this.modelFields.join(','),
          ...data.map(record => 
            this.modelFields.map(field => {
              const value = record[field];
              return typeof value === 'object' ? JSON.stringify(value) : value;
            }).map(val => `"${val}"`).join(',')
          )
        ].join('\n');

        const blob = new Blob([csv], { type: 'text/csv' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${this.selectedModel}-export-${new Date().toISOString().split('T')[0]}.csv`;
        a.click();
        URL.revokeObjectURL(url);
      } else {
        const json = JSON.stringify(data, null, 2);
        const blob = new Blob([json], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${this.selectedModel}-export-${new Date().toISOString().split('T')[0]}.json`;
        a.click();
        URL.revokeObjectURL(url);
      }

      this.analyticsService.trackAction('data-exported', 'data-management', { 
        model: this.selectedModel, 
        format: this.exportFormat,
        count: data.length 
      });
    } catch (error) {
      this.analyticsService.trackError('export-failed', 'data-management', { error: error.message });
    }
  }

  toggleSelectAll(): void {
    if (this.allSelected) {
      this.selectedRecords = [];
    } else {
      this.selectedRecords = this.paginatedRecords.map(record => record.id);
    }
  }

  sortBy(field: string): void {
    if (this.sortField === field) {
      this.sortDirection = this.sortDirection === 'asc' ? 'desc' : 'asc';
    } else {
      this.sortField = field;
      this.sortDirection = 'asc';
    }
    this.analyticsService.trackAction('data-sorted', 'data-management', { field, direction: this.sortDirection });
  }

  editRecord(record: any): void {
    this.editingRecord = record;
    this.formData = { ...record };
    this.showEditModal = true;
    this.analyticsService.trackAction('edit-record-opened', 'data-management', { model: this.selectedModel, id: record.id });
  }

  async deleteRecord(record: any): Promise<void> {
    if (!confirm(`Are you sure you want to delete this ${this.selectedModel}?`)) {
      return;
    }

    try {
      const mutation = `
        mutation Delete${this.selectedModel}($input: Delete${this.selectedModel}Input!) {
          delete${this.selectedModel}(input: $input) {
            id
          }
        }
      `;

      await this.graphqlClient.query(mutation, { input: { id: record.id } });
      await this.loadModelData();
      this.analyticsService.trackAction('record-deleted', 'data-management', { model: this.selectedModel, id: record.id });
    } catch (error) {
      this.analyticsService.trackError('delete-failed', 'data-management', { error: error.message });
    }
  }

  async impersonateUser(user: any): Promise<void> {
    if (!confirm(`Impersonate user ${user.name}? This will log you in as this user.`)) {
      return;
    }

    try {
      this.analyticsService.trackAction('user-impersonation', 'data-management', { 
        targetUserId: user.id, 
        targetUserName: user.name 
      });
      
      window.location.href = '/';
    } catch (error) {
      this.analyticsService.trackError('impersonation-failed', 'data-management', { error: error.message });
    }
  }

  formatTimestamp(timestamp: string): string {
    return new Date(timestamp).toLocaleString();
  }

  closeModals(): void {
    this.showCreateModal = false;
    this.showEditModal = false;
    this.formData = {};
    this.editingRecord = null;
  }

  onRecordSelectionChange(recordId: string, selected: boolean): void {
    if (selected) {
      this.selectedRecords.push(recordId);
    } else {
      this.selectedRecords = this.selectedRecords.filter(id => id !== recordId);
    }
  }

  isRecordSelected(recordId: string): boolean {
    return this.selectedRecords.includes(recordId);
  }

  onPageSizeChange(): void {
    this.currentPage = 1;
  }

  previousPage(): void {
    if (this.currentPage > 1) {
      this.currentPage--;
    }
  }

  nextPage(): void {
    if (this.currentPage < this.totalPages) {
      this.currentPage++;
    }
  }
}
<div class="data-management">
  <div class="management-header">
    <h2>Data Management</h2>
    <div class="model-selector">
      <select [(ngModel)]="selectedModel" (change)="onModelChange()">
        <option value="">Select Model</option>
        <option *ngFor="let model of availableModels" [value]="model">{{ model }}</option>
      </select>
      <button (click)="refreshData()" class="btn-secondary">Refresh</button>
      <button (click)="exportData()" class="btn-primary" [disabled]="!selectedModel">
        Export {{ exportFormat }}
      </button>
      <select [(ngModel)]="exportFormat">
        <option value="CSV">CSV</option>
        <option value="JSON">JSON</option>
      </select>
    </div>
  </div>

  <div *ngIf="selectedModel" class="model-management">
    <div class="actions-bar">
      <button (click)="showCreateModal = true" class="btn-primary">
        Create New {{ selectedModel }}
      </button>
      <div class="search-bar">
        <input 
          [(ngModel)]="searchQuery"
          placeholder="Search records..." 
          class="search-input"
        />
      </div>
    </div>

    <div class="data-table">
      <table>
        <thead>
          <tr>
            <th>
              <input 
                type="checkbox" 
                (change)="toggleSelectAll()"
                [checked]="allSelected"
              />
            </th>
            <th *ngFor="let field of modelFields" (click)="sortBy(field)">
              {{ field }}
              <span *ngIf="sortField === field">
                {{ sortDirection === 'asc' ? '↑' : '↓' }}
              </span>
            </th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let record of paginatedRecords">
            <td>
              <input 
                type="checkbox" 
                [value]="record.id"
                [checked]="isRecordSelected(record.id)"
                (change)="onRecordSelectionChange(record.id, $event.target.checked)"
              />
            </td>
            <td *ngFor="let field of modelFields">
              <div *ngIf="field.includes('At')" class="timestamp">
                {{ formatTimestamp(record[field]) }}
              </div>
              <div *ngIf="!field.includes('At') && typeof record[field] === 'object'">
                <details>
                  <summary>Object</summary>
                  <pre>{{ record[field] | json }}</pre>
                </details>
              </div>
              <div *ngIf="!field.includes('At') && typeof record[field] !== 'object'">
                {{ record[field] }}
              </div>
            </td>
            <td class="actions">
              <button (click)="editRecord(record)" class="btn-sm btn-secondary">
                Edit
              </button>
              <button (click)="deleteRecord(record)" class="btn-sm btn-danger">
                Delete
              </button>
              <button 
                *ngIf="selectedModel === 'User'" 
                (click)="impersonateUser(record)"
                class="btn-sm btn-warning"
              >
                Impersonate
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="pagination">
      <button 
        (click)="previousPage()" 
        [disabled]="currentPage <= 1"
        class="btn-secondary"
      >
        Previous
      </button>
      <span>Page {{ currentPage }} of {{ totalPages }}</span>
      <button 
        (click)="nextPage()" 
        [disabled]="currentPage >= totalPages"
        class="btn-secondary"
      >
        Next
      </button>
      <select [(ngModel)]="pageSize" (change)="onPageSizeChange()">
        <option value="10">10 per page</option>
        <option value="25">25 per page</option>
        <option value="50">50 per page</option>
        <option value="100">100 per page</option>
      </select>
    </div>
  </div>
</div>
